name: stress
on: workflow_dispatch
jobs:
  stress:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt-get update
          sudo apt-get install linux-tools-$(uname -r)
          gcc -O3 stress.c -o stress
          sudo $(dpkg -L linux-tools-$(uname -r) | grep -m1 -E '/perf$') stat ./stress
