name: stress
on: workflow_dispatch
jobs:
  stress:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt-get install linux-tools-6.14.0-1017-azure linux-tools-azure
          gcc -O3 stress.c -o stress
          perf stat ./stress
